export const UPDATE_NEW_BOOK_TITLE = 'UPDATE_NEW_BOOK_TITLE'
export const UPDATE_NEW_BOOK_AUTHOR = 'UPDATE_NEW_BOOK_AUTHOR'
export const UPDATE_NEW_BOOK_ISBN = 'UPDATE_NEW_BOOK_ISBN'
export const UPDATE_NEW_BOOK_QTY = 'UPDATE_NEW_BOOK_QTY'

export const UPDATE_CHECKED_OUT_BOOKS = 'UPDATE_CHECKED_OUT_BOOKS'
export const UPDATE_CHECKED_IN_BOOKS = 'UPDATE_CHECKED_IN_BOOKS'
export const SORT_BOOKS_ALPHABETICALLY = 'SORT_BOOKS_ALPHABETICALLY'

export const SEARCH_BOOK_TITLE = 'SEARCH_BOOK_TITLE'

export const ADD_NEW_BOOK = 'ADD_NEW_BOOK'
export const REMOVE_BOOK = 'REMOVE_BOOK'
export const CHECK_OUT_BOOK = 'CHECK_OUT_BOOK'
export const CHECK_IN_BOOK = 'CHECK_IN_BOOK'
export const EDIT_BOOK = 'EDIT_BOOK'