export const UPDATED_NEW_BOOK_TITLE = 'UPDATED_NEW_BOOK_TITLE'
export const UPDATED_NEW_BOOK_AUTHOR = 'UPDATED_NEW_BOOK_AUTHOR'
export const UPDATED_NEW_BOOK_ISBN = 'UPDATED_NEW_BOOK_ISBN'
export const UPDATED_NEW_BOOK_QTY = 'UPDATED_NEW_BOOK_QTY'

export const UPDATED_CHECKED_OUT_BOOKS = 'UPDATED_CHECKED_OUT_BOOKS'
export const UPDATED_CHECKED_IN_BOOKS = 'UPDATED_CHECKED_IN_BOOKS'
export const SORTED_BOOKS_ALPHABETICALLY = 'SORTED_BOOKS_ALPHABETICALLY'

export const UPDATED_SEARCH_TERM = 'UPDATED_SEARCH_TERM'

export const SELECTED_BOOK = 'SELECTED_BOOK'
export const ADDED_NEW_BOOK = 'ADDED_NEW_BOOK'
export const REMOVED_BOOK = 'REMOVEED_BOOK'
export const CHECKED_OUT_BOOK = 'CHECKED_OUT_BOOK'
export const CHECKED_IN_BOOK = 'CHECKED_IN_BOOK'
export const EDITED_BOOK = 'EDITED_BOOK'